### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by greigbl** [ojacques/hubot-apiai#11]
Hi ojacques,

Have found this module very helpful. However, I noticed that you do not have any licensing in place and was wondering if you would be willing to make your intentions clear in that respect. Thanks in advance for considering this.

**Comment by ojacques** [comment]
Thanks @zerowon01 . I added [the license](https://github.com/ojacques/hubot-apiai/blob/master/LICENSE) - Apache v2.

**Comment by greigbl** [comment]
Thank you very much.
