### ISSUE TITLE
behind proxy

### ISSUE THREAD

**Issue by dCode91** [ojacques/hubot-apiai#4]
Cannot use this behind a proxy... I tried to configured proxy in many different ways but it does not work i get this error:
Error: write EPROTO 140736486470592:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:../deps/openssl/openssl/ssl/s23_clnt.c:769:

  at exports._errnoException (util.js:1018:11)
  at WriteWrap.afterWrite (net.js:800:14)

**Comment by ojacques** [comment]
Yes, I got caught by this too. Can you check if [this](https://github.com/slackapi/hubot-slack/issues/372#issuecomment-270892846) works for you too?

**Comment by ojacques** [comment]
@danielcrisan - does the above work?

**Comment by ojacques** [comment]
Answered, closing.

**Comment by rastangineer** [comment]
I'm having the same issue, I have tried the solution mentioned by @ojacques but no luck.

[Tue Apr 03 2018 21:06:26 GMT+0000 (UCT)] ERROR { Error: write EPROTO 139799624234784:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:../deps/openssl/openssl/ssl/s23_clnt.c:802:

  at _errnoException (util.js:1022:11)
  at WriteWrap.afterWrite (net.js:867:14)
 code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
