### ISSUE TITLE
how to call a api and print its json responce?

### ISSUE THREAD

**Issue by kavya05** [ojacques/hubot-apiai#7]
hey! #helpplease
i am developing a bot for my company and i want to call the api in natural language and print its json responce as the result, as far as now, im able to talk to my bot wit api.ai in back end , but i need help in knowing how to call a api and print its json responce.

example:
user: bot can you show me my storage space left in my VM?
**bot should call a api and return json responce to user**
bot:  here is the answer to your question..
     **displays json responce**

**Comment by ojacques** [comment]
Although not related to this hubot-api library, [this line](https://github.com/ojacques/hubot-apiai/blob/master/src/apiai.coffee#L52) calls the API.AI back-end, using json. 
[This line](https://github.com/ojacques/hubot-apiai/blob/master/src/apiai.coffee#L52) shows the output (again, json). 

As you can see, `hubot-apiai` uses the [apiai library](https://www.npmjs.com/package/apiai), which is what you are looking for.

Hope this helps.
