### ISSUE TITLE
how to extract values of entities/parameter name in api.ai?

### ISSUE THREAD

**Issue by kavya05** [ojacques/hubot-apiai#8]
hey! thanks for your previous reply it helped me a lot,
I have one more query , I need to extract the **values of entities/parameter name in api.ai** so that i can pass those values in a POST statement in my companies internal API. I have attached a screen shot of my project. i have highlighted the values i need to extract. is it something like **entity.value** ?

**please help me out**
![apiai](https://user-images.githubusercontent.com/30457237/35135491-9f3701e8-fd03-11e7-9b79-c6d5dbff3f6c.PNG)

thanks in advance :)

**Comment by ojacques** [comment]
@kavya05, in your [listener hubot script](https://github.com/ojacques/hubot-apiai#create-listener-scripts), you will use the parameters like:
```
params.bytes
params.ssl_type
params.number
```

It's really straightforward
